question_data = [
    {"category": "General Knowledge",
     "type": "boolean", "difficulty": "easy",
     "question": "Gumbo is a stew that originated in Louisiana.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "French is an official language in Canada.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Bulls are attracted to the color red.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Romanian belongs to the Romance language family, shared with French,"
                 " Spanish, Portuguese and Italian. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;27 Club&quot; is a term used to refer to a list of famous actors,"
                 " musicians, and artists who died at the age of 27.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Scotland voted to become an independent country during the referendum from September 2014.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
